### ISSUE TITLE
Have contributed? Get your name on the list here! (July 2021)

### ISSUE THREAD

**Issue by Hans5958** [ScratchAddons/contributors#136] opened 2021-07-10 15:42 UTC
So, you have contributed in the Scratch Addons development, whether it's code, docs, or even an idea? If so, you are eligible for your name to be added to the list, and also be featured on https://scratchaddons.com/contributors.

We are following the all-contributors specification, and this repository is the catch-all contributors list on all repositories on the Scratch Addons' repository.

To be added, **comment on this issue with a mention to @all-contributors like the example below**. You actually don't need to follow this template exactly.

```
@all-contributors add <GitHub username> for <contributions>
```

`<GitHub username>` is **your username on GitHub**, not Scratch!

`<contributions>` is one or many, of the valid types on [the emoji key](https://allcontributors.org/docs/en/emoji-key).

For example:

```
@all-contributors add @Hans5958 for bug
@all-contributors add @Hans5958 for code, translation, and doc
@all-contributors can you add @Hans5958 for ideas?
```

[Read more here](https://allcontributors.org/docs/en/bot/usage).

**Doing so will create a pull request, which we need to review and merge to have your name on the website.** You can do this in [the comment section of the issue below](#new_comment_field), or make a new issue (but it is discouraged).

To speed up the process, you can give proof of your contribution (a link, a picture, anything), but please put it on the created PR as messages on this issue is not monitored.

# [⬇️ Go directly to the new comment field! ⬇️](#new_comment_field)

For organization members, 

1. If you wanted to add someone else, you can do this here, but I recommend you to do it on #6, so people know that their name will be added on the list. That is, if you mention the issue/PR on the other repositories.
2. Please use the **squash merge**, not the commit merge.

**Comment by GitHub027** [comment] 2021-07-17 07:27
hey

**Comment by GitHub027** [comment] 2021-07-17 07:30
@all-contributors add @GitHub027  for bug

**Comment by GitHub027** [comment] 2021-07-17 07:31
> @GitHub027
> 
> @GitHub027 already contributed before to bug

I don't see

**Comment by GitHub027** [comment] 2021-07-17 08:12
@all-contributors add @mouse_sausage  for bug

**Comment by CST1229** [comment] 2021-07-20 08:18
> @all-contributors add @mouse_sausage for bug

> **I [wrote](https://github.com/ScratchAddons/contributors/issues/71#issuecomment-862291480):**
> 
> You use GitHub usernames for this, not Scratch usernames.



> > @GitHub027
> > @GitHub027 already contributed before to bug
> 
> I don't see

#132

**Comment by Sreehari521** [comment] 2021-07-26 06:44
I also want to be a contributer. But I hav'nt contributed. What should I do?

**Comment by Hans5958** [comment] 2021-07-26 06:53
@Sreehari521 

Read this section on the FAQ. https://scratchaddons.com/docs/faq/#how-can-i-contribute-to-scratch-addons

**Comment by sfederici** [comment] 2021-07-26 15:47
I guess I have bug reports and ideas too. But I will let you decide if they are enough :)

**Comment by Sreehari521** [comment] 2021-07-27 02:08
@all-contributors add @Sreehari521  for ideas

**Comment by Sreehari521** [comment] 2021-07-27 09:25
I have contributed and I am not in the list , why?

**Comment by Sreehari521** [comment] 2021-07-27 09:25
I have contributed and I am not in the list , why?

**Comment by Sreehari521** [comment] 2021-07-27 09:25
I have contributed and I am not in the list , why?

**Comment by CST1229** [comment] 2021-07-27 09:28
> 
> 
> I have contributed and I am not in the list , why?

The pull request has to be merged for you to appear.

**Comment by Sreehari521** [comment] 2021-07-27 09:30
> > I have contributed and I am not in the list , why?
> 
> The pull request has to be merged for you to appear.

How can it be merged?

**Comment by CST1229** [comment] 2021-07-27 11:00
> 
> 
> > > I have contributed and I am not in the list , why?
> > 
> > 
> > The pull request has to be merged for you to appear.
> 
> How can it be merged?

It's merged when the managers of this repository decide to. To speed it up you can provide proof.

**Comment by GitHub027** [comment] 2021-07-28 10:09
> I have contributed and I am not on the list

same

**Comment by CST1229** [comment] 2021-07-28 10:41
> 
> 
> > I have contributed and I am not on the list
> 
> same

Please answer https://github.com/ScratchAddons/contributors/pull/132#issuecomment-864365180.

**Comment by GitHub027** [comment] 2021-07-28 12:30
Have contributed? Get your name on the list here! (July 2021)
#136
Hans5958 opened this issue 18 days ago · 17 comments
I S S U E

**Comment by GitHub027** [comment] 2021-07-28 12:31
What if I got banned, can I add an addon?
If yes, I wish I make: "Ignore bans [recommended]

**Comment by GitHub027** [comment] 2021-07-28 12:37
@all-contributors add @Hans5958 for bug
@all-contributors add @Hans5958 for code, translation, and doc
@all-contributors can you add @Hans5958 for ideas?

**Comment by GitHub027** [comment] 2021-07-28 12:38
please add @Someone for code, doc and infra

**Comment by GitHub027** [comment] 2021-07-28 12:39
@all-contributors add @Someone for code, doc, and infra

**Comment by RedGuy12** [comment] 2021-07-28 12:45
> What if I got banned, can I add an addon?

As long as you can still test it.

> If yes, I wish I make: "Ignore bans [recommended]"

Impossible

**Comment by GitHub027** [comment] 2021-07-28 17:19
> > What if I got banned, can I add an addon?
> 
> As long as you can still test it.
> 
> > If yes, I wish I make: "Ignore bans [recommended]"
> 
> Impossible

I will try

**Comment by GitHub027** [comment] 2021-07-28 17:23
> @CST1229
> 
> Could not find the user `mouse_sausage` on Github.

My username is mouse_sausage btw

**Comment by CST1229** [comment] 2021-07-28 17:33
> 
> 
> > @CST1229
> > Could not find the user `mouse_sausage` on Github.
> 
> My username is mouse_sausage btw

It was your quote triggering it.

**Comment by Samq64** [comment] 2021-07-28 23:49
@all-contributors add @Samq64 for bug reports and code.

**Comment by CodeGuy92** [comment] 2021-07-30 20:55
@all-contributors add @CodeGuy92 for code, ideas

**Comment by CodeGuy92** [comment] 2021-07-30 20:55
o that was fast-

**Comment by GitHub027** [comment] 2021-08-04 17:48
ADD ME TO THE LIST OR I WILL HACK YOU!!! >:(

**Comment by CST1229** [comment] 2021-08-04 18:22
> 
> 
> ADD ME TO THE LIST OR I WILL HACK YOU!!! >:(

[Did you even read anything of this?](https://github.com/ScratchAddons/contributors/pull/132#issuecomment-889990533)

**Comment by alphakids381** [comment] 2021-08-05 03:18
@all-contributors add <alphakids381> for <contributions>

**Comment by Medericoder** [comment] 2021-08-05 15:17
@all-contributors add @Medericoder for bug

**Comment by era2010-coder** [comment] 2021-08-05 18:10
@all-contributors can you add @era2010-coder for ideas?

**Comment by Ninjadragonmc** [comment] 2021-08-29 08:16
@all-contributors add @Ninjadragonmc for bug

**Comment by Medericoder** [comment] 2021-08-30 08:56
@all-contributors add <Medericoder> for <ideas>

**Comment by Medericoder** [comment] 2021-08-30 08:57
@all-contributors add <Medericoder> for <ideas>

**Comment by Medericoder** [comment] 2021-08-30 08:57
@all-contributors add Medericoder for ideas

**Comment by e-coders** [comment] 2021-09-15 18:45
Hello! I want to also Contribute Scratch Addons. How Did I Contribute it?

**Comment by RedGuy12** [comment] 2021-09-15 19:06
> Hello! I want to also Contribute Scratch Addons. How Did I Contribute it?

@e-coders read https://scratchaddons.com/docs/faq/#how-can-i-contribute-to-scratch-addons

**Comment by GreypathPro** [comment] 2021-09-16 06:04
Hey! I've contributed by adding more language features.
**@Greypath**

**Comment by LegoManiac04** [comment] 2021-09-20 00:13
@all-contributors add LegoManiac04 for ideas, bug

**Comment by e-coders** [comment] 2021-09-20 06:54
I've not contributed, I want to make something. please help me!!

**Comment by Sreehari521** [comment] 2021-09-20 13:19
@allcontributors  add @Sreehari521 for ideas, code and bugs

**Comment by e-coders** [comment] 2021-09-21 07:28
@allcontributors add @e-coders  for Ideas, code, Fixes and bugs

**Comment by Medericoder** [comment] 2021-09-23 18:43
@all-contributors add @Medericoder for translation

**Comment by e-coders** [comment] 2021-09-25 17:43
@all-contributors add @e-coders for an Addon

**Comment by e-coders** [comment] 2021-09-25 17:44
@all-contributors add @e-coders for code, bug, ideas, and test

**Comment by e-coders** [comment] 2021-09-25 17:44
I've added this - https://github.com/ScratchAddons/ScratchAddons/pull/3554 Project Fullscreen

**Comment by RedGuy12** [comment] 2021-09-25 18:07
Closing because it works when closed still

**Closed by RedGuy12** 2021-09-25 18:07 UTC

**Comment by e-coders** [comment] 2021-09-25 18:17
?

**Comment by RedGuy12** [comment] 2021-09-25 18:23
> ?

@all-contributors still works when the issue is closed

**Comment by RedGuy12** [comment] 2021-09-26 12:59
@all-contributors Add @Nik0lyaZ as a contributor for translation.

**Comment by RedGuy12** [comment] 2021-09-26 13:00
@all-contributors add @e-coders for ideas

**Comment by RedGuy12** [comment] 2021-09-26 13:00
Hm

**Comment by e-coders** [comment] 2021-09-26 14:22
Oh!! Thanks!!

**Comment by Miala-python** [comment] 2021-10-10 17:12
> @Miala-python
> 
> I've put up [a pull request](https://github.com/ScratchAddons/contributors/pull/159) to add @Miala-python! tada

Thank you

**Comment by fupicat** [comment] 2021-10-18 22:30
@all-contributors add @Fupicat for bug and translation

**Comment by ilbailba** [comment] 2021-10-30 16:59
@all-contributors add @ilbailba for Turkish translations

**Comment by e-coders** [comment] 2021-10-30 17:00
hi

**Comment by ilbailba** [comment] 2021-10-30 17:01
hi @e-coders !

**Comment by e-coders** [comment] 2021-10-30 17:02
Hi!! I'm in site of Scratch addons contributors. Hope you will also come on!

**Comment by ilbailba** [comment] 2021-10-30 17:03
hopefully... how long will it take me to get to the contributors site?

**Comment by ilbailba** [comment] 2021-10-30 18:23
hopefully... how long will it take me to get to the contributors site @e-coders ?

**Comment by LegoManiac04** [comment] 2021-10-30 18:40
@ilbailba Once a contributor checks out the pull request the bot made, and confirms that you have contributed to said things, the pull request will be merged and you'll be added.

It all depends when a contributor checks it out, but expect maybe a couple days or so ^^

**Comment by ilbailba** [comment] 2021-10-30 18:49
> @ilbailba Once a contributor checks out the pull request the bot made, and confirms that you have contributed to said things, the pull request will be merged and you'll be added.
> 
> It all depends when a contributor checks it out, but expect maybe a couple days or so ^^

thanks!

**Comment by chills-vibe** [comment] 2021-11-02 04:01
@all-contributors add @chills-vibe for Vietnamese translation.

**Comment by iqnite** [comment] 2021-11-10 16:50
@all-contributors add iqnite for bug

**Comment by johnny263** [comment] 2021-12-20 12:15
@all-contributors add @johnn6263 for translation

**Comment by johnny263** [comment] 2021-12-20 12:15
@all-contributors add @johnn263 for translation

**Comment by johnny263** [comment] 2021-12-20 12:15
@all-contributors add @johnny263 for translation

**Comment by johnny263** [comment] 2021-12-20 12:22
really?

**Comment by johnny263** [comment] 2021-12-20 12:29
@all-contributors add @johnny263 for translation

**Comment by johnny263** [comment] 2021-12-20 12:30
Why I can not see my name on contributed?

**Comment by RedGuy12** [comment] 2021-12-20 13:35
> Why I can not see my name on contributed?

i need to confirm your contribution first

**Comment by hasnain123333** [comment] 2021-12-28 06:24
Hasnain12333 helped for bug and i did'nt see my credits

**Comment by LegoManiac04** [comment] 2021-12-28 07:06
@hasnain123333 - Contributions aren't added automatically,. 
You or someone else will comment here following the [directions in the top post](https://github.com/ScratchAddons/contributors/issues/136#issue-941274484), which will open a PR for a contributor to look over.

Since I happened to see this, I'll do it for you- 
@all-contributors add hasnain123333 for bug

**Comment by jumpycoke** [comment] 2022-01-14 03:24
@all-contributors add @jumpycoke for suggesting ideas

**Comment by jumpycoke** [comment] 2022-01-17 04:49
@all-contributors add @jumpycoke for suggesting new addons

**Comment by jumpycoke** [comment] 2022-01-17 04:50
@all-contributors add @jumpycoke for suggesting ideas

**Comment by RedGuy12** [comment] 2022-01-17 16:13
@all-contributors add newcat07 for translation

**Comment by RedGuy12** [comment] 2022-01-17 16:57
@all-contributors add kebabo for translation

**Comment by iqnite** [comment] 2022-01-27 19:47
@all-contributors add iqnite for bug
